all:
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ~/.ssh/id_ed25519
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_common_args: >
      -o ProxyJump=ubuntu@93.77.179.155
      -o StrictHostKeyChecking=no

  children:

    webservers:
      hosts:
        web-1:
          ansible_host: 10.0.2.15
        web-2:
          ansible_host: 10.0.3.26

    monitoring:
      hosts:
        prometheus:
          ansible_host: 10.0.2.18

    elasticsearch_group:
      hosts:
        elasticsearch:
          ansible_host: 10.0.2.25

    kibana_group:
      hosts:
        kibana:
          ansible_host: 10.0.0.24
